### ISSUE TITLE
Decide on tools for QC pipelines for Salmonella

### ISSUE THREAD

**Issue by karinlag** [NorwegianVeterinaryInstitute/IRIDA_Plugin_Development_Steps#1]
This issue has been broken into 3 sub issues to make it easier to follow and fix it 
- [ ] Decide on contamination tool #26
- [ ] Decide on "How to calculate coverage" #25
- [ ] Decide on "Intraspecies contamination" #

**Comment by Camilsek** [comment]
Will this be one pipeline for raw reads and one for assembly?

**Comment by 01schau** [comment]
@Camilsek I think so, but I do not know what the pipeline developer has in mind... @ajkarloss

**Comment by ajkarloss** [comment]
We have agreed to use FastQC, Karken2 and calculate the coverage normally. So, I am closing that.
