### ISSUE TITLE
Add all sequenced Salmonella to VIGAS-P

### ISSUE THREAD

**Issue by Camilsek** [NorwegianVeterinaryInstitute/IRIDA_Plugin_Development_Steps#12]
Identify all Salmonella we have sequenced, compare with what is in VIGAS-P and upload te isoaltes that are missing to get an complete database.

**Comment by Camilsek** [comment]
I have downloaded the list of samples from VIGAS-P and compared to the isolates we have sequenced in house.
A few samples were duplicates in VIGAS-P and have been deleted from the list of samples.
Some samples will need to be renamed with proper naming.
@01schau and @Camilsek will go through the list of samples that are not yet in VIGAS-P and provide @ajkarloss with a list of samples that will need to be included in VIGAS-P.

**Comment by Camilsek** [comment]
Renamed samples in VIGAS-P

**Comment by 01schau** [comment]
Jannice needs to figure out if she has sequenced any Salmonella outside VI (GATC, etc)

**Comment by Camilsek** [comment]
[Salmonella_in_NGS_list_20220928.xlsx](https://github.com/NorwegianVeterinaryInstitute/IRIDA_Plugin_Development_Steps/files/9663712/Salmonella_in_NGS_list_20220928.xlsx)

@01schau  can you have a look at this file and see if it's correct that you are responsible for these isolates and that you can find them so Jeevan can upload to VIGAS-P?
@Camilsek will do the same for the other isolates and also find some additional sequences sequenced by GATC.

**Comment by 01schau** [comment]
[Salmonella_in_NGS_list_20220928_jss.xlsx](https://github.com/NorwegianVeterinaryInstitute/IRIDA_Plugin_Development_Steps/files/9665999/Salmonella_in_NGS_list_20220928_jss.xlsx)

I have checked the list and entered missing information - marked green color.

**Comment by karinlag** [comment]
STatus: @Camilsek should check list and then @ajkarloss should upload.

**Comment by Camilsek** [comment]
[Salmonella_in_NGS_list_20220928_jss_cs.xlsx](https://github.com/NorwegianVeterinaryInstitute/IRIDA_Plugin_Development_Steps/files/9703933/Salmonella_in_NGS_list_20220928_jss_cs.xlsx)

@ajkarloss : I have added my sequences to the same Excel sheet as Jannice, VIGASP_jeevan. For the data that are located on Nird I have not added the name of R1 and R2, but hope you are able to locate the files by the sample name. Please let me know if this is difficult.
Be aware that for some of the tar files there are more read files that should not go into the Salmonella directory.

**Comment by ajkarloss** [comment]
I will look at it and fix a time to upload them

**Comment by ajkarloss** [comment]
All the samples are transferred to VIGASP
