### ISSUE TITLE
Validate MLST pipeline for salmonella

### ISSUE THREAD

**Issue by karinlag** [NorwegianVeterinaryInstitute/IRIDA_Plugin_Development_Steps#9]
Decide on which and how many isolates to include

**Comment by Camilsek** [comment]
Started with the validation document based on the validation document from ResPointFinder

**Comment by Camilsek** [comment]
@ajkarloss can you find out when the MLST database for Salmonella was downloaded?

**Comment by Camilsek** [comment]
I have validated the method and have a first draft for the validation report.
I therefore close this issue and open a new one for finalizing the validation report.
